### ISSUE TITLE
WebGL fallbacks

### ISSUE THREAD

**Issue by patrickfuller** [patrickfuller/imolecule#10]
For users that don't have webGL, we should have a functional fallback (even if its slower). three.js supports a couple of backends, so falling back to CSS3 or SVG should be simple enough.

I tried this a while back in the [svg](https://github.com/patrickfuller/imolecule/tree/svg) branch - may be worth looking in to.

**Comment by bjonnh** [comment]
You can have a look at my feature/canvas-fallback branch. It support fallback to the simple CanvasRenderer. I don't know anything about the SVGRenderer, looks like it is an external renderer.

**Comment by patrickfuller** [comment]
Very useful! I'll merge in your edits, although I'm going to avoid adding another option to the python method.
