### ISSUE TITLE
404 on local nbextensions

### ISSUE THREAD

**Issue by oliveirarodolfo** [patrickfuller/imolecule#12]
I'm getting a `404` when running the `imolecule` nbextension:

```bash
[W 10:47:15.960 NotebookApp] 404 GET /nbextensionsimolecule.min.js?v=20150729104512 (127.0.0.1) 
0.00ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=python2
```

I believe this has to do with the following line in the [notebook.py](https://github.com/patrickfuller/imolecule/blob/master/python/notebook.py#L12) file:

```python 
local_path = os.path.join("nbextensions", filename)
```

While running it on windows, the `local_path` is joined using `\\` instead of `/` and that might be causing the message and actually never loading the local `imolecule.min.js` library.

**Comment by patrickfuller** [comment]
I was able to replicate on my windows VM, and you're correct as to the reason. I'll push a quick change and update the version.
