### ISSUE TITLE
[FR] conda package

### ISSUE THREAD

**Issue by ctk3b** [patrickfuller/imolecule#16]
I'm happy to create the skeleton for a travis/conda build system if you can turn on travis for this repo and generate a binstar key.

**Comment by patrickfuller** [comment]
Definitely. Let's deal with this after getting everything else working.

**Comment by patrickfuller** [comment]
Added the token in ef72b4a181c59fd2571e81cef086dd93a80bf518, and everything's working here. Let me know if it's good on your end.

**Comment by ctk3b** [comment]
Works! Thanks so much.
