### ISSUE TITLE
Jupyter notebook compatibility warning

### ISSUE THREAD

**Issue by azag0** [patrickfuller/imolecule#22]
Importing imolecule in IPython 4 (Jupyter) generates following warning:

> ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)

P.S. Great project, thanks!

**Comment by patrickfuller** [comment]
This fix is already fixed in the development version, but I never incremented the version on PyPI.

Try `pip install -U imolecule` and see if the issue's fixed.

**Comment by azag0** [comment]
Ah, of course. Works without a problem.
