### ISSUE TITLE
Save snapshot

### ISSUE THREAD

**Issue by CorySimon** [patrickfuller/imolecule#25]
This is an excellent and much needed tool, thank you!

Is there a way to save a snapshot of the molecule as e.g. a .png file, such as:

    molecule = imolecule.draw("CC1(C(N2C(S1)C(C2=O)NC(=O)CC3=CC=CC=C3)C(=O)O)C")
    molecule.savefig("mymolecule.png", format="png")

Further, a way to host this interactive viewer on a website? e.g. some .html code to copy and paste into Jekyll?

**Comment by patrickfuller** [comment]
The images are definitely doable. According to [this stackoverflow post](http://stackoverflow.com/questions/15558418/how-do-you-save-an-image-from-a-three-js-canvas), it shouldn't be much work. I'll do this when I get some time.

Regarding the interactive viewer, you definitely can. You can use the source code from the examples as a starting point. If you have any questions on implementing, let me know.

**Comment by CorySimon** [comment]
It looks like `mof.html` in the `examples` folder is what I am looking for.

Can you please provide an example of how to use IMolecule or your script `format_converter.py` to convert e.g. a .cssr file to a JSON to use in `mof.html`?

**Comment by patrickfuller** [comment]
The intended use of the library was through the UI. If you `pip install`ed this, typing `imolecule` will pop open a web UI. Drag and drop your .cssr file in, and then click save as -> json.

If you didn't go this route, there's also a format converter shim I use for testing. From [this code](https://github.com/patrickfuller/imolecule/blob/master/imolecule/format_converter.py#L204-L213), you can run with e.g.

```
python format_converter.py myfile.cssr cssr json > molecule.json
```

I should probably rewrite it with argparse and expose it through e.g. `imolecule convert`, but haven't gotten there.

**Comment by patrickfuller** [comment]
Saving molecule renders is now possible like so:

<img width="672" alt="screen shot 2015-11-04 at 10 04 59 pm" src="https://cloud.githubusercontent.com/assets/1449833/10959626/4d08565e-8340-11e5-8ede-e203226f574d.png">

Setting `show_save=True` displays a save icon that can be clicked to save the current camera angle on the molecule. Let me know if it works for you.

**Comment by CorySimon** [comment]
Awesome, thank you. Can you please make an option to change the dpi? The resolution is very low in the images that I save.

**Comment by patrickfuller** [comment]
The current approach saves a render of the current buffer, so it's tied to
the size of the viewing window.

As a short-term solution, you can expand the size of your imolecule render
before saving.

As a longer term solution, I like the idea of rendering in an off-screen
buffer. Itll be some work to see if it's possible, but it'd make saving
more consistent.

**Comment by patrickfuller** [comment]
25e6899f8cb27479d88080bf878d47b75202a549 renders at high resolution. Current default is to scale width to 2560px and maintain aspect ratio.

Let me know if this works for you.
