### ISSUE TITLE
How to generate the .min.js files?

### ISSUE THREAD

**Issue by bjonnh** [patrickfuller/imolecule#4]
I'd like to make changes to imolecule.js (trying to correct the other issue I raised), but couldn't find a way to regenerate the imolecule.min.js correctly…

**Comment by patrickfuller** [comment]
To compact js, use a minifier. I use [uglifyJS](https://github.com/mishoo/UglifyJS), and the command I run is:

```
uglifyjs three.min.js TrackballControls.js ShaderToon.js imolecule.js > build/imolecule.min.js
```

I'll add this to the readme.

**Comment by bjonnh** [comment]
Wonderful, thanks!
